### ISSUE TITLE
panic:cmd failed: 1: tar xf /Users/monicagomez/.tea/tea.xyz/var/www/imagemagick.org-7.1.0.61+darwin+x86-64.tar.xz -C /Users/monicagomez/.tea

### ISSUE THREAD

**Issue by cloudflare-wangler** [teaxyz/cli#401] opened 2023-02-24 18:00 UTC
----------------------------------------------------->> attachment begin
Error: cmd failed: 1: tar xf /Users/monicagomez/.tea/tea.xyz/var/www/imagemagick.org-7.1.0.61+darwin+x86-64.tar.xz -C /Users/monicagomez/.tea
    at run (file:///opt/tea.xyz/src/v0.22.2/src/utils/index.ts:212:34)
    at async install (file:///opt/tea.xyz/src/v0.22.2/src/prefab/install.ts:84:9)
    at async install (file:///opt/tea.xyz/src/v0.22.2/src/hooks/useExec.ts:100:25)
    at async default (file:///opt/tea.xyz/src/v0.22.2/src/hooks/useExec.ts:71:25)
    at async file:///opt/tea.xyz/src/v0.22.2/src/app.ts:37:63
<<----------------------------------------------------- attachment end

**Comment by mxcl** [comment] 2023-02-26 12:12
Dupe of #400. Can you please provide the output I requested in #400? Thank you.

**Closed by mxcl** 2023-02-26 12:12 UTC
