### ISSUE TITLE
after leaving dev environment with dev off  or change directory cause the zsh terminal freeze.

### ISSUE THREAD

**Issue by haliliceylan** [teaxyz/cli#733] opened 2023-09-15 20:42 UTC
after activating dev, when I try to "dev off" or "cd ..". Terminal session is freezing.

<img width="436" alt="Screenshot 2023-09-15 at 22 42 19" src="https://github.com/teaxyz/cli/assets/33789758/7a9c5b79-91a1-4958-891b-35bbf3a8c9ff">

**Comment by mxcl** [comment] 2023-09-16 12:53
hmm this is a serious bug. I see you are running in VSCode. Does this happen in a normal terminal too?

**Comment by haliliceylan** [comment] 2023-09-16 13:01
Yes, I am using as shell env Oh-my-zsh btw.

**Comment by haliliceylan** [comment] 2023-09-16 17:10
with bash, its working fine.

<img width="765" alt="image" src="https://github.com/teaxyz/cli/assets/33789758/e93a752c-993c-4586-9684-0ff2f5dbccee">

**Comment by haliliceylan** [comment] 2023-09-16 17:13
I disabled zsh and all .zshrc file, even with default installation. Its freezing.

<img width="789" alt="Screenshot 2023-09-16 at 19 12 43" src="https://github.com/teaxyz/cli/assets/33789758/6da60cf7-a0ba-4ca7-b6ba-97288bdb7705">

**Comment by mxcl** [comment] 2023-09-17 12:57
is your zsh the macOS default or provided by brew or something else?

**Comment by haliliceylan** [comment] 2023-09-17 13:16
Default.

**Comment by haliliceylan** [comment] 2023-09-17 13:17
How can I debug ? Maybe I can try strace with dev ?

**Comment by haliliceylan** [comment] 2023-09-17 19:37
I could not trace with that, because dev and tea command is pointing a function.
![image](https://github.com/teaxyz/cli/assets/33789758/49f7f76a-73e1-4cee-a1e9-17ba90e5a261)

**Comment by haliliceylan** [comment] 2023-09-21 07:08
Hello, this problem is really affecting the development environment. Could you please show me how to provide more information (Debug, Verbose) about this so that we can better understand the error.

**Comment by sporkd** [comment] 2023-09-26 21:56
This is not a terminal freeze. It's actually the prompt getting set to `""`.  Looks like a duplicate of https://github.com/teaxyz/cli/issues/747

**Comment by mxcl** [comment] 2023-09-28 11:12
Thanks @sporkd, I will fix this stat

**Closed** 2023-09-28 11:37 UTC
Labels: bug
